### ISSUE TITLE
r-universe build errors

### ISSUE THREAD

**Issue by wlandau** [ropensci/jagstargets#18]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/jagstargets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/jagstargets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

Looks like r-universe Mac and Windows builds are erroring out, e.g. https://github.com/r-universe/ropensci/runs/3725483247?check_suite_focus=true. @jeroen, anything on my end I can do to fix this? NB in the `jagstargets` workflow files I had to write my own commands to install JAGS on Mac and Windows.

https://github.com/ropensci/jagstargets/blob/df8d3d0401f108e01b78ff4b755e0834ac71b371/.github/workflows/check.yaml#L55-L69

https://github.com/ropensci/jagstargets/blob/df8d3d0401f108e01b78ff4b755e0834ac71b371/.github/workflows/check.yaml#L84-L88

**Comment by jeroen** [comment]
The best solution would be to make the package installable, even when JAGS is not available: https://github.com/ropensci/jagstargets/pull/22.

**Comment by wlandau** [comment]
Fair enough, if it is the only way I guess I will go with it.

**Comment by jeroen** [comment]
Maybe we can come up with some way to install extra tools in r-univesre at some point, but for now this is the easiest solution.

By the way you should update your ubuntu version in CI because 16.04 is being retired (you will find the builds take very long). 

This is now best practice: https://github.com/r-lib/actions/blob/master/examples/check-standard.yaml
