### ISSUE TITLE
JOSS Reviewer comments.

### ISSUE THREAD

**Issue by JonasMoss** [ropensci/jagstargets#27]
Hi! Seeing some thorough work here! =)

Here are some minor issues (may update this list in the following days; I'll tell you when I'm done.):
- [x] The name of the package in https://github.com/ropensci/jagstargets/blob/main/man/jagstargets-package.Rd is wrong.
- [x] You have made a vignette, but I'm having trouble finding it in R itself. I.e., vignette(package = "jagstargets") says that no vignette is found. (Using the development version).

**Comment by wlandau** [comment]
The package name should now be fixed in the latest commit. To load the vignettes locally, I recommend installing the package with `remotes::install_github("ropensci/jagstargets", build_vignettes = TRUE, force = TRUE)`. `build_vignettes` is `FALSE` by default in `install_github()`, which I think works here because the `simulation.Rmd` vignette takes a while to render, and the vignettes are rendered at https://docs.ropensci.org/jagstargets/articles/introduction.html and https://docs.ropensci.org/jagstargets/articles/simulation.html and kept up to date with continuous integration.

**Comment by JonasMoss** [comment]
Aha, thought it was something like that (about the vignettes)! =)
